### ISSUE TITLE
Improve styling of notifications in toolbar: icons and colors

### ISSUE THREAD

**Issue by sypets** [peterbenke/pb_notifications#11]
This is current version (installed via TER with TYPO3 v12, without extension [fontawesome_provider](https://extensions.typo3.org/extension/fontawesome_provider)): 

-------------

![image](https://github.com/user-attachments/assets/07e431ca-a20c-4e91-8354-69c67c6aaba4)

------------

For example: This is what I would like: 

------------

![image](https://github.com/user-attachments/assets/bfe5428d-150b-479c-afcb-ad124507f972)

------------

in particular, the

* icons: 
![image](https://github.com/user-attachments/assets/2ca008a9-0a6d-4c41-b428-3ce3d6c60e6e)
![image](https://github.com/user-attachments/assets/d3ecf6c9-9dab-4b7c-9ad2-f016d3d220cd)

* different color for warning and info
* icon for "Alle Benachrichtigungen anzeigen": 
![image](https://github.com/user-attachments/assets/bbf2f293-ddc9-42e3-bcf0-8dbdfc5b04e6)

* (there is also a line break between header and text, but that was not intentional)

Example code:

**Resources/Private/Templates/ToolbarMenu/DropDown.html** 

This is just an example, ideally the colors could be set via CSS as in PR : https://github.com/peterbenke/pb_notifications/pull/7/files

```
<f:if condition="{notification.type} == 1">
  <f:then>
    <span class="text-danger">
      <core:icon identifier="actions-exclamation-circle-alt"/>&nbsp;
       <f:format.date date="{notification.date}" format="{f:translate(key:'LLL:EXT:pb_notifications/Resources/Private/Language/locallang.xlf:notifications.list.dateFormat')}" />
       <br>
       <strong>{notification.title}</strong>:</span>
      </f:then>
       <f:else>
         <span class="text-primary">
         <core:icon identifier="actions-info-circle"/>&nbsp;
         <f:format.date date="{notification.date}" format="{f:translate(key:'LLL:EXT:pb_notifications/Resources/Private/Language/locallang.xlf:notifications.list.dateFormat')}" />
          <br>
         <strong>{notification.title}</strong>:</span>
      </f:else>
</f:if>
```

Here, the font awesome icon should be replaced by core icon:

```
<ul class="dropdown-list">
    <li id="pbnotifications_listnotifications">
        <a href="#" class="dropdown-item"
           data-dispatch-action="TYPO3.ModuleMenu.showModule"
           data-dispatch-args-list="user_PbNotificationsNotifications"
        >
            <span
-                   <i class="fa fa-list"></i>
+                  <core:icon identifier="actions-list"/>
                      &nbsp; <f:translate key="toolbaritem.allNotifications" extensionName="pb_notifications" />
                 </span>
        </a>
    </li>
</ul>


```

**Comment by sypets** [comment]
Note: in TYPO3 v12 font-awesome is no longer installed in the BE by default, can be installed:

`composer require friendsoftypo3/fontawesome-provider `

But then it should be set as requirement.

I would recommend to just use core icons:

* https://typo3.github.io/TYPO3.Icons/

e.g.

```
<core:icon identifier="actions-exclamation-circle-alt"/>
 <core:icon identifier="actions-info-circle"/>
```

and for the list: e.g. [actions-list](https://typo3.github.io/TYPO3.Icons/icons/actions/actions-list.html)

` <core:icon identifier="actions-list"/>`

**Comment by peterbenke** [comment]
Hello,
font awesome is already set as requirement, see:
https://github.com/peterbenke/pb_notifications/blob/12.4.2/composer.json

**Comment by sypets** [comment]
I tested on installation without composer. This uses the requirements in ext_emconf.php.
